# Generated by Django 6.0 on 2025-12-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habit', '0003_aboutcontent_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
