# Generated by Django 6.0 on 2025-12-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habit', '0004_simplesociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(blank=True, max_length=100, null=True)),
                ('platform_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Social',
            },
        ),
        migrations.DeleteModel(
            name='SimpleSocialLink',
        ),
    ]
